name: observability-on-loadbalancer

services:
  prometheus:
    image: prom/prometheus:v2.52.0           # latest stable as of 2025-04-24
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - prom_data:/prometheus                # long-term storage
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.external-url=http://prometheus:9090"
    ports:
      - "9090:9090"
    depends_on:
      - node-exporter
      - alertmanager
    networks:
      - observability

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.8.1
    container_name: node-exporter
    pid: host                                 # lets it read /proc from the host
    network_mode: host                        # so it reports real host IP
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'                 # needed because of host PID namespace
    volumes:
      - '/:/host:ro,rslave'                   # read-only bind mount of host FS

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - am_data:/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    ports:
      - "9093:9093"
    networks:
      - observability

volumes:
  prom_data:
  am_data:

networks:
  observability:
    driver: bridge
